### ISSUE TITLE
BUG: "string" is not a valid rule name

### ISSUE THREAD

**Issue by matak** [rindeal/allegro-php-client#6]
Respect\Validation\Exceptions\ComponentException

"string" is not a valid rule name

bug is somewhere here

ApiCredentials
                     Validator::string()->noWhitespace()->notEmpty()->length(4)->assert($value);

**Comment by rindeal** [comment]
caused by an update in respect/validation (1.0.* -> 1.1.*), fixed in https://github.com/rindeal/allegro-php-client/commit/81e326e5f36abc135dfe49fa7aa17bb77f476c42
